remote_theme: pages-themes/minimal@v0.2.0
site_url: https://rathi-prashant.github.io/awesome_devops_examples/
plugins:
- jekyll-remote-theme

title: Awesome DevOps examples

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]